import React, { useState, useEffect, useMemo, useCallback, useRef } from 'react'
import { useAuthStore } from '@/contexts/auth'
import { useApi } from '@/hooks/useApi'
import clsx from 'clsx'
import './CalendarView.css'

interface CalendarEvent {
  id: number
  title: string
  start_date: string
  start_time?: string | null
  end_date?: string | null
  end_time?: string | null
  category: string
  priority: 'low' | 'medium' | 'high'
  assignee?: string | null
  description?: string | null
  is_completed?: boolean
}

interface Todo {
  id: number
  title: string
  due_date?: string | null
  priority: 'low' | 'medium' | 'high'
  assignee?: string | null
  description?: string | null
  is_completed: boolean
}

const ASSIGNEE_COLORS = {
  groom: {
    background: '#3b82f6',
    border: 'rgba(59, 130, 246, 0.4)',
    shadow: 'rgba(59, 130, 246, 0.35)',
  },
  bride: {
    background: '#ec4899',
    border: 'rgba(236, 72, 153, 0.4)',
    shadow: 'rgba(236, 72, 153, 0.35)',
  },
  both: {
    background: '#8b5cf6',
    border: 'rgba(139, 92, 246, 0.4)',
    shadow: 'rgba(139, 92, 246, 0.35)',
  },
} as const

const today = new Date()
const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`

export default function CalendarView() {
  const authStore = useAuthStore()
  const { request } = useApi()

  const [currentDate, setCurrentDate] = useState(new Date())
  const [events, setEvents] = useState<CalendarEvent[]>([])
  const [todos, setTodos] = useState<Todo[]>([])
  const [weddingDate, setWeddingDate] = useState<string | null>(null)
  const [dDay, setDDay] = useState<number | null>(null)
  const [showAutoGeneratedEvents, setShowAutoGeneratedEvents] = useState(true)
  const [selectedDate, setSelectedDate] = useState<string | null>(todayStr)

  const [showEventModal, setShowEventModal] = useState(false)
  const [editingEventId, setEditingEventId] = useState<number | null>(null)

  const [eventForm, setEventForm] = useState({
    title: '',
    start_date: new Date().toISOString().split('T')[0],
    start_time: '',
    timeHour: '',
    timeMinute: '',
    timePeriod: 'AM' as 'AM' | 'PM',
    category: 'general',
    priority: 'medium' as 'low' | 'medium' | 'high',
    assignee: 'both',
    description: '',
    is_completed: false,
  })

  const canAccess = useMemo(() => true, [])

  const currentMonthText = useMemo(() => {
    const year = currentDate.getFullYear()
    const month = currentDate.getMonth() + 1
    return `${year}년 ${month}월`
  }, [currentDate])

  const calendarDays = useMemo(() => {
    const year = currentDate.getFullYear()
    const month = currentDate.getMonth()
    const firstDay = new Date(year, month, 1)
    const startDate = new Date(firstDay)
    startDate.setDate(startDate.getDate() - startDate.getDay())

    const days: Array<{
      date: Date
      isCurrentMonth: boolean
      isToday: boolean
      events: CalendarEvent[]
    }> = []

    for (let i = 0; i < 42; i++) {
      const date = new Date(startDate)
      date.setDate(startDate.getDate() + i)
      const year = date.getFullYear()
      const month = String(date.getMonth() + 1).padStart(2, '0')
      const day = String(date.getDate()).padStart(2, '0')
      const dateStr = `${year}-${month}-${day}`

      let dayEvents = events.filter((e) => e.start_date === dateStr)

      if (weddingDate && weddingDate === dateStr) {
        const hasWeddingEvent = dayEvents.some((e) => e.title.includes('예식일') || e.category === 'wedding')
        if (!hasWeddingEvent) {
          dayEvents = [
            ...dayEvents,
            {
              id: -1,
              title: '예식일',
              start_date: dateStr,
              category: 'wedding',
              priority: 'high',
              assignee: 'both',
              description: '예식일',
            } as CalendarEvent,
          ]
        }
      }

      const isToday = date.toDateString() === new Date().toDateString()

      days.push({
        date,
        isCurrentMonth: date.getMonth() === month,
        isToday,
        events: dayEvents,
      })
    }

    return days
  }, [currentDate, events, weddingDate])

  // 로그인 상태 변경 감지
  useEffect(() => {
    const userId = authStore.user?.id
    if (userId && authStore.isAuthenticated) {
      loadData()
    } else {
      setEvents([])
      setTodos([])
      setWeddingDate(null)
      setDDay(null)
    }
  }, [authStore.user?.id, authStore.isAuthenticated])

  useEffect(() => {
    if (authStore.user?.id && authStore.isAuthenticated) {
      loadData()
    }
  }, [])

  async function loadData() {
    const userId = authStore.user?.id
    if (!userId) return

    try {
      await Promise.all([loadEvents(), loadWeddingDate()])
      updateDDay()
      await loadTodos()
    } catch (err) {
      console.error('loadData: 데이터 로드 중 오류 발생:', err)
    }
  }

  async function loadWeddingDate() {
    if (!authStore.user?.id) {
      setWeddingDate(null)
      setDDay(null)
      return
    }

    try {
      const res = await request<{ message: string; data: { wedding_date: string | null } }>(
        `/calendar/wedding-date`,
        { method: 'GET' }
      )

      if (res && typeof res === 'object') {
        if ('message' in res && res.message === 'wedding_date_retrieved') {
          if (res.data && res.data.wedding_date) {
            setWeddingDate(res.data.wedding_date)
            updateDDay()
          } else {
            setWeddingDate(null)
          }
        } else {
          setWeddingDate(null)
        }
      } else {
        setWeddingDate(null)
      }
    } catch (err: any) {
      console.error('예식일 로드 실패:', err)
      setWeddingDate(null)
      setDDay(null)
    }
  }

  function updateDDay() {
    if (!weddingDate) {
      setDDay(null)
      return
    }

    const [year, month, day] = weddingDate.split('-').map(Number)
    const wedding = new Date(year, month - 1, day)
    wedding.setHours(0, 0, 0, 0)

    const today = new Date()
    today.setHours(0, 0, 0, 0)

    const diff = Math.ceil((wedding.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
    setDDay(diff)
  }

  async function setWeddingDateHandler() {
    const date = weddingDate
    if (!date || !date.match(/^\d{4}-\d{2}-\d{2}$/)) {
      alert('올바른 날짜 형식(YYYY-MM-DD)을 입력해주세요.')
      return
    }

    const [year, month, day] = date.split('-').map(Number)
    const dateObj = new Date(year, month - 1, day)
    if (
      dateObj.getFullYear() !== year ||
      dateObj.getMonth() !== month - 1 ||
      dateObj.getDate() !== day
    ) {
      alert('유효하지 않은 날짜입니다.')
      return
    }

    try {
      const res = await request<{ message: string; data: { wedding_date: string } }>(
        `/calendar/wedding-date`,
        {
          method: 'POST',
          body: { wedding_date: date },
        }
      )

      if (res.message === 'wedding_date_set' && res.data?.wedding_date) {
        const savedDate = res.data.wedding_date
        setWeddingDate(savedDate)
        updateDDay()

        const [savedYear, savedMonth] = savedDate.split('-').map(Number)
        setCurrentDate(new Date(savedYear, savedMonth - 1, 1))

        const [displayYear, displayMonth, displayDay] = savedDate.split('-').map(Number)
        const formattedDate = `${displayYear}년 ${displayMonth}월 ${displayDay}일`

        alert(`예식일이 ${formattedDate}로 설정되었습니다.\n\n"타임라인 자동 생성" 버튼을 눌러 일정을 생성할 수 있습니다.`)
      } else {
        throw new Error('예식일 설정 응답이 올바르지 않습니다.')
      }
    } catch (err: any) {
      console.error('예식일 설정 실패:', err)
      const errorMessage = err?.data?.message || err?.message || '알 수 없는 오류'
      alert(`예식일 설정에 실패했습니다.\n오류: ${errorMessage}`)
    }
  }

  async function generateTimeline() {
    let targetDate = weddingDate
    if (!targetDate) {
      try {
        const res = await request<{ data: { wedding_date: string | null } }>(
          `/calendar/wedding-date`,
          { method: 'GET' }
        )
        if (res.data?.wedding_date) {
          targetDate = res.data.wedding_date
          setWeddingDate(targetDate)
        } else {
          alert('예식일을 먼저 설정해주세요.')
          return
        }
      } catch (err) {
        console.error('예식일 로드 실패:', err)
        alert('예식일을 먼저 설정해주세요.')
        return
      }
    }

    if (events.length > 0) {
      if (!confirm('기존 일정을 모두 삭제하고 새 타임라인을 생성하시겠습니까?')) return
    }

    try {
      const response = await request(`/calendar/timeline/generate`, {
        method: 'POST',
        body: {
          wedding_date: targetDate,
          user_preferences: {},
        },
      })

      if (response.message === 'timeline_generated' || response.message === 'timeline_created') {
        alert('타임라인이 생성되었습니다.')
        await loadData()
      } else {
        throw new Error('타임라인 생성 응답이 올바르지 않습니다.')
      }
    } catch (err: any) {
      console.error('타임라인 생성 실패:', err)
      const errorMessage = err?.data?.message || err?.message || '알 수 없는 오류'
      alert(`타임라인 생성에 실패했습니다.\n오류: ${errorMessage}`)
    }
  }

  async function loadEvents() {
    const userId = authStore.user?.id
    if (!userId) {
      setEvents([])
      return
    }

    try {
      const res = await request<{ message: string; data: { events: CalendarEvent[] } }>(
        `/calendar/todos`,
        { method: 'GET' }
      )
      if (res.message === 'todos_retrieved') {
        setEvents(res.data.events || [])
      } else {
        setEvents([])
      }
    } catch (err) {
      console.error('일정 로드 실패:', err)
      setEvents([])
    }
  }

  async function loadTodos() {
    const userId = authStore.user?.id
    if (!userId) {
      setTodos([])
      return
    }

    try {
      if (selectedDate) {
        const dayEvents = events.filter((e) => e.start_date === selectedDate)
        setTodos(
          dayEvents.map((event) => ({
            id: event.id,
            title: event.title,
            due_date: event.start_date,
            priority: event.priority,
            assignee: event.assignee || 'both',
            description: event.description || null,
            is_completed: event.is_completed || false,
          }))
        )
      } else {
        const todoEvents = events.filter((e) => e.category === 'todo')
        setTodos(
          todoEvents.map((event) => ({
            id: event.id,
            title: event.title,
            due_date: event.start_date,
            priority: event.priority,
            assignee: event.assignee || 'both',
            description: event.description || null,
            is_completed: event.is_completed || false,
          }))
        )
      }
    } catch (err) {
      console.error('할일 로드 실패:', err)
      setTodos([])
    }
  }

  useEffect(() => {
    loadTodos()
  }, [selectedDate, events])

  const handleDateClick = useCallback((dateStr: string) => {
    if (selectedDate === dateStr) {
      setSelectedDate(null)
    } else {
      setSelectedDate(dateStr)
    }
  }, [selectedDate])

  function prevMonth() {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() - 1, 1))
  }

  function nextMonth() {
    setCurrentDate(new Date(currentDate.getFullYear(), currentDate.getMonth() + 1, 1))
  }

  function parseTimeTo12Hour(time24: string | null | undefined): { hour: string; minute: string; period: 'AM' | 'PM' } {
    if (!time24) {
      return { hour: '', minute: '', period: 'AM' }
    }
    const [hour, minute] = time24.split(':')
    const hourNum = parseInt(hour, 10)
    if (hourNum === 0) {
      return { hour: '12', minute: minute || '', period: 'AM' }
    } else if (hourNum < 12) {
      return { hour: hour, minute: minute || '', period: 'AM' }
    } else if (hourNum === 12) {
      return { hour: '12', minute: minute || '', period: 'PM' }
    } else {
      return { hour: String(hourNum - 12), minute: minute || '', period: 'PM' }
    }
  }

  function formatTimeTo24Hour(hour: string, minute: string, period: 'AM' | 'PM'): string {
    if (!hour || !minute) return ''
    let hourNum = parseInt(hour, 10)
    if (isNaN(hourNum) || hourNum < 1 || hourNum > 12) return ''
    if (period === 'PM' && hourNum !== 12) {
      hourNum += 12
    } else if (period === 'AM' && hourNum === 12) {
      hourNum = 0
    }
    const minuteNum = parseInt(minute, 10)
    if (isNaN(minuteNum) || minuteNum < 0 || minuteNum > 59) return ''
    return `${String(hourNum).padStart(2, '0')}:${String(minuteNum).padStart(2, '0')}`
  }

  function openEventModal(event?: CalendarEvent) {
    if (event) {
      setEditingEventId(event.id)
      const timeParts = parseTimeTo12Hour(event.start_time)
      setEventForm({
        title: event.title,
        start_date: event.start_date,
        start_time: event.start_time || '',
        timeHour: timeParts.hour,
        timeMinute: timeParts.minute,
        timePeriod: timeParts.period,
        category: event.category || 'general',
        priority: event.priority,
        assignee: event.assignee || 'both',
        description: event.description || '',
        is_completed: event.is_completed || false,
      })
    } else {
      setEditingEventId(null)
      setEventForm({
        title: '',
        start_date: new Date().toISOString().split('T')[0],
        start_time: '',
        timeHour: '',
        timeMinute: '',
        timePeriod: 'AM',
        category: 'general',
        priority: 'medium',
        assignee: 'both',
        description: '',
        is_completed: false,
      })
    }
    setShowEventModal(true)
  }

  function closeEventModal() {
    setShowEventModal(false)
    setEditingEventId(null)
  }

  function openTodoModal(todo?: Todo) {
    if (todo) {
      const event: CalendarEvent = {
        id: todo.id,
        title: todo.title,
        start_date: todo.due_date || new Date().toISOString().split('T')[0],
        start_time: null,
        end_date: null,
        end_time: null,
        category: 'todo',
        priority: todo.priority,
        assignee: todo.assignee || 'both',
        description: todo.description || null,
        is_completed: todo.is_completed,
      }
      openEventModal(event)
    } else {
      setEditingEventId(null)
      setEventForm({
        title: '',
        start_date: new Date().toISOString().split('T')[0],
        start_time: '',
        timeHour: '',
        timeMinute: '',
        timePeriod: 'AM',
        category: 'todo',
        priority: 'medium',
        assignee: 'both',
        description: '',
        is_completed: false,
      })
      setShowEventModal(true)
    }
  }

  async function createEvent() {
    if (!eventForm.title || !eventForm.start_date) {
      alert('제목과 날짜를 입력해주세요.')
      return
    }

    try {
      const time24 = formatTimeTo24Hour(eventForm.timeHour, eventForm.timeMinute, eventForm.timePeriod)

      if (editingEventId) {
        await request(`/calendar/todos/${editingEventId}`, {
          method: 'PUT',
          body: {
            title: eventForm.title,
            start_date: eventForm.start_date,
            start_time: time24 || null,
            category: eventForm.category,
            priority: eventForm.priority,
            assignee: eventForm.assignee,
            description: eventForm.description || null,
            is_completed: eventForm.is_completed,
          },
        })
        alert('일정이 수정되었습니다.')
      } else {
        await request(`/calendar/todos`, {
          method: 'POST',
          body: {
            title: eventForm.title,
            start_date: eventForm.start_date,
            start_time: time24 || null,
            category: eventForm.category,
            priority: eventForm.priority,
            assignee: eventForm.assignee,
            description: eventForm.description || null,
            is_completed: eventForm.is_completed,
          },
        })
        alert('일정이 추가되었습니다.')
      }
      closeEventModal()
      await loadData()
    } catch (err) {
      console.error(err)
      alert(editingEventId ? '일정 수정에 실패했습니다.' : '일정 추가에 실패했습니다.')
    }
  }

  async function deleteEvent(eventId: number) {
    if (!confirm('정말 이 일정을 삭제하시겠습니까?')) return

    try {
      await request(`/calendar/todos/${eventId}`, {
        method: 'DELETE',
      })
      closeEventModal()
      await loadData()
      alert('일정이 삭제되었습니다.')
    } catch (err) {
      console.error(err)
      alert('일정 삭제에 실패했습니다.')
    }
  }

  async function deleteTodo(todoId: number) {
    if (!confirm('정말 이 할일을 삭제하시겠습니까?')) return

    try {
      await request(`/calendar/todos/${todoId}`, {
        method: 'DELETE',
      })
      await loadData()
      await loadEvents()
      alert('할일이 삭제되었습니다.')
    } catch (err) {
      console.error('할일 삭제 오류:', err)
      alert('할일 삭제에 실패했습니다.')
    }
  }

  async function toggleTodo(todoId: number) {
    const todo = todos.find((t) => t.id === todoId)
    if (!todo) return

    try {
      await request(`/calendar/todos/${todoId}`, {
        method: 'PUT',
        body: {
          is_completed: !todo.is_completed,
        },
      })
      await loadTodos()
      await loadEvents()
    } catch (err) {
      console.error('할일 상태 변경 오류:', err)
      alert('할일 상태 변경에 실패했습니다.')
    }
  }

  function getPriorityClass(priority: string) {
    return priority === 'high' ? 'high' : priority === 'medium' ? 'medium' : 'low'
  }

  function getAssigneeClass(assignee: string | null | undefined) {
    if (assignee === 'groom') return 'assignee-groom'
    if (assignee === 'bride') return 'assignee-bride'
    return 'assignee-both'
  }

  function getEventStyle(event: CalendarEvent): React.CSSProperties {
    if (event.category === 'wedding' || event.id === -1) {
      return {}
    }

    if (event.category === 'todo' || event.id < -1000) {
      const colors = ASSIGNEE_COLORS[(event.assignee as keyof typeof ASSIGNEE_COLORS) || 'both'] || ASSIGNEE_COLORS.both
      return {
        background: `linear-gradient(135deg, ${colors.background}dd, ${colors.background}aa)`,
        backgroundColor: `${colors.background}dd`,
        borderColor: colors.border,
        boxShadow: `0 1px 3px ${colors.shadow}`,
        borderStyle: 'dashed',
        borderWidth: '1px',
      }
    }

    const colors = ASSIGNEE_COLORS[(event.assignee as keyof typeof ASSIGNEE_COLORS) || 'both'] || ASSIGNEE_COLORS.both

    return {
      background: colors.background,
      backgroundColor: colors.background,
      borderColor: colors.border,
      boxShadow: `0 2px 6px ${colors.shadow}`,
    }
  }

  function handleEventClick(event: CalendarEvent) {
    if (event.id === -1) {
      return
    }

    if (event.id < -1000) {
      const todoId = -event.id - 1000
      const todo = todos.find((t) => t.id === todoId)
      if (todo) {
        openTodoModal(todo)
      }
      return
    }

    openEventModal(event)
  }

  const handleDateKeydown = useCallback((event: React.KeyboardEvent<HTMLInputElement>, field: 'start_date' | 'wedding_date') => {
    const input = event.currentTarget

    if (['Backspace', 'Delete', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Tab', 'Enter'].includes(event.key)) {
      return
    }

    if (event.ctrlKey || event.metaKey) {
      return
    }

    if (!/^\d$/.test(event.key)) {
      event.preventDefault()
      return
    }

    const currentValue = input.value.replace(/\D/g, '')
    const newValue = currentValue + event.key

    if (newValue.length > 8) {
      event.preventDefault()
      return
    }

    let formatted = newValue
    if (newValue.length > 4) {
      formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6)
    }
    if (newValue.length > 6) {
      formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6) + '-' + newValue.slice(6, 8)
    }

    if (newValue.length === 4) {
      event.preventDefault()
      formatted = newValue + '-'
      updateDateValue(field, formatted)
      setTimeout(() => {
        input.value = formatted
        input.setSelectionRange(5, 5)
      }, 0)
      return
    }

    if (newValue.length === 6) {
      event.preventDefault()
      formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6) + '-'
      updateDateValue(field, formatted)
      setTimeout(() => {
        input.value = formatted
        input.setSelectionRange(formatted.length, formatted.length)
      }, 0)
      return
    }

    event.preventDefault()
    formatted = formatDateValue(newValue)
    updateDateValue(field, formatted)
    setTimeout(() => {
      input.value = formatted
      input.setSelectionRange(formatted.length, formatted.length)
    }, 0)
  }, [])

  function formatDateValue(digits: string): string {
    if (digits.length <= 4) {
      return digits
    } else if (digits.length <= 6) {
      return digits.slice(0, 4) + '-' + digits.slice(4, 6)
    } else {
      return digits.slice(0, 4) + '-' + digits.slice(4, 6) + '-' + digits.slice(6, 8)
    }
  }

  function updateDateValue(field: 'start_date' | 'wedding_date', value: string) {
    if (field === 'start_date') {
      setEventForm({ ...eventForm, start_date: value })
    } else if (field === 'wedding_date') {
      setWeddingDate(value)
    }
  }

  const handleDateInput = useCallback((event: React.ChangeEvent<HTMLInputElement>, field: 'start_date' | 'wedding_date') => {
    const input = event.target
    const value = input.value

    if (value.match(/^\d{4}-\d{2}-\d{2}$/)) {
      updateDateValue(field, value)
      return
    }

    const digits = value.replace(/\D/g, '').slice(0, 8)
    const formatted = formatDateValue(digits)
    updateDateValue(field, formatted)

    setTimeout(() => {
      if (input.value !== formatted) {
        input.value = formatted
      }
    }, 0)
  }, [])

  const handleDatePaste = useCallback((event: React.ClipboardEvent<HTMLInputElement>, field: 'start_date' | 'wedding_date') => {
    event.preventDefault()
    const input = event.currentTarget
    const pastedText = event.clipboardData?.getData('text') || ''
    const digits = pastedText.replace(/\D/g, '').slice(0, 8)
    const formatted = formatDateValue(digits)

    updateDateValue(field, formatted)

    setTimeout(() => {
      input.value = formatted
      input.setSelectionRange(formatted.length, formatted.length)
    }, 0)
  }, [])

  const handleTimeHourChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/\D/g, '')
    let hourValue = value.length > 2 ? value.slice(0, 2) : value
    let period = eventForm.timePeriod

    const hourNum = parseInt(value, 10)
    if (!isNaN(hourNum)) {
      if (hourNum >= 13 && hourNum <= 23) {
        period = 'PM'
        hourValue = String(hourNum - 12)
      } else if (hourNum === 0) {
        period = 'AM'
        hourValue = '12'
      } else if (hourNum > 23) {
        hourValue = '12'
      } else if (hourNum > 12) {
        hourValue = '12'
      }
    }

    setEventForm({ ...eventForm, timeHour: hourValue, timePeriod: period })
  }, [eventForm])

  const handleTimeMinuteChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value.replace(/\D/g, '')
    let minuteValue = value.length > 2 ? value.slice(0, 2) : value

    const minuteNum = parseInt(value, 10)
    if (!isNaN(minuteNum) && minuteNum > 59) {
      minuteValue = '59'
    }

    setEventForm({ ...eventForm, timeMinute: minuteValue })
  }, [eventForm])

  return (
    <section className="section" id="calendar">
      <div className="container" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
        <div className="page-title">
          <h1>📅 개인화 일정 관리(캘린더)</h1>
          <p>D-Day 기반 타임라인 자동 생성 + Todo 리스트</p>
        </div>

        {/* 예식일 설정 */}
        <div className="card">
          <div className="wedding-date-section">
            <label style={{ fontWeight: 600 }}>예식일:</label>
            <input
              type="text"
              id="weddingDateInput"
              value={weddingDate || ''}
              placeholder="YYYY-MM-DD"
              maxLength={10}
              onKeyDown={(e) => handleDateKeydown(e, 'wedding_date')}
              onChange={(e) => handleDateInput(e, 'wedding_date')}
              onPaste={(e) => handleDatePaste(e, 'wedding_date')}
            />
            <button className="btn primary" type="button" onClick={setWeddingDateHandler}>
              설정
            </button>
            <button className="btn" type="button" onClick={generateTimeline}>
              타임라인 자동 생성
            </button>
            <label style={{ display: 'flex', alignItems: 'center', gap: '8px', marginLeft: '12px', cursor: 'pointer' }}>
              <input
                type="checkbox"
                checked={showAutoGeneratedEvents}
                onChange={(e) => setShowAutoGeneratedEvents(e.target.checked)}
                style={{ width: '18px', height: '18px', cursor: 'pointer' }}
              />
              <span style={{ fontSize: '14px', color: 'var(--text)' }}>자동 생성 일정 표시</span>
            </label>
          </div>
          {dDay !== null && (
            <div style={{ fontSize: '18px', fontWeight: 600, color: 'var(--accent)', marginTop: '12px' }}>
              {dDay > 0 && <span>D-{dDay}</span>}
              {dDay === 0 && <span>D-Day!</span>}
              {dDay < 0 && <span>D+{Math.abs(dDay)}</span>}
            </div>
          )}
        </div>

        {/* 캘린더 */}
        <div className="card">
          <div className="calendar-header">
            <h2 style={{ margin: 0 }}>캘린더</h2>
            <div className="calendar-controls">
              <div className="month-navigation">
                <button className="btn month-btn" type="button" onClick={prevMonth}>
                  ◀
                </button>
                <span className="month-text">{currentMonthText}</span>
                <button className="btn month-btn" type="button" onClick={nextMonth}>
                  ▶
                </button>
              </div>
              <button className="btn primary" type="button" onClick={() => openEventModal()}>
                일정 추가
              </button>
            </div>
          </div>
          {/* 일정 색상 범례 */}
          <div
            style={{
              display: 'flex',
              gap: '16px',
              marginBottom: '16px',
              padding: '12px',
              background: 'var(--soft)',
              borderRadius: '8px',
              flexWrap: 'wrap',
            }}
          >
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <div style={{ width: '16px', height: '16px', borderRadius: '4px', background: '#3b82f6' }}></div>
              <span style={{ fontSize: '13px', color: 'var(--text)' }}>신랑 일정</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <div style={{ width: '16px', height: '16px', borderRadius: '4px', background: '#ec4899' }}></div>
              <span style={{ fontSize: '13px', color: 'var(--text)' }}>신부 일정</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <div style={{ width: '16px', height: '16px', borderRadius: '4px', background: '#8b5cf6' }}></div>
              <span style={{ fontSize: '13px', color: 'var(--text)' }}>공동 일정</span>
            </div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <div
                style={{
                  width: '16px',
                  height: '16px',
                  borderRadius: '4px',
                  background: 'linear-gradient(135deg, var(--accent), var(--accent-2))',
                }}
              ></div>
              <span style={{ fontSize: '13px', color: 'var(--text)' }}>예식일</span>
            </div>
          </div>
          <div className="calendar-grid">
            {['일', '월', '화', '수', '목', '금', '토'].map((dayName) => (
              <div key={dayName} style={{ textAlign: 'center', fontWeight: 600, padding: '8px' }}>
                {dayName}
              </div>
            ))}
            {calendarDays.map((day, idx) => {
              const dateStr = `${day.date.getFullYear()}-${String(day.date.getMonth() + 1).padStart(2, '0')}-${String(day.date.getDate()).padStart(2, '0')}`
              return (
                <div
                  key={idx}
                  className={clsx('calendar-day', {
                    'other-month': !day.isCurrentMonth,
                    today: day.isToday,
                    'selected-date': selectedDate === dateStr,
                  })}
                  onClick={() => handleDateClick(dateStr)}
                >
                  <div className="day-number">{day.date.getDate()}</div>
                  {day.events.map((event) => (
                    <div
                      key={`${event.id}-${event.start_date}`}
                      className={clsx('event-item', getPriorityClass(event.priority), getAssigneeClass(event.assignee), {
                        'wedding-event': event.category === 'wedding' || event.id === -1,
                        'todo-event': event.category === 'todo' || event.id < -1000,
                      })}
                      style={getEventStyle(event)}
                      title={event.description || event.title}
                      onClick={(e) => {
                        e.stopPropagation()
                        handleEventClick(event)
                      }}
                    >
                      {event.title}
                    </div>
                  ))}
                </div>
              )
            })}
          </div>
        </div>

        {/* Todo 리스트 */}
        <div className="card todo-section">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: '16px', gap: '16px' }}>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                <h2 style={{ margin: 0 }}>할일 리스트</h2>
                {selectedDate && (
                  <>
                    <span style={{ fontSize: '14px', color: 'var(--accent-2)', fontWeight: 600 }}>({selectedDate})</span>
                    <button
                      type="button"
                      onClick={() => {
                        setSelectedDate(null)
                        loadTodos()
                      }}
                      style={{
                        padding: '4px 8px',
                        background: 'var(--soft)',
                        border: '1px solid var(--line)',
                        borderRadius: '4px',
                        color: 'var(--muted)',
                        fontSize: '12px',
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = 'var(--danger)'
                        e.currentTarget.style.color = '#fff'
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'var(--soft)'
                        e.currentTarget.style.color = 'var(--muted)'
                      }}
                    >
                      필터 해제
                    </button>
                  </>
                )}
              </div>
              <p style={{ margin: 0, fontSize: '13px', color: 'var(--muted)', lineHeight: 1.5 }}>
                <strong>📅 일정 vs 📋 할일:</strong> 일정은 특정 날짜와 시간에 고정된 이벤트(예: 웨딩홀 방문, 드레스 피팅)이고,
                할일은 매일매일 작게 쌓이는 체크리스트(예: 청첩장 주문 확인, 하객 명단 작성)입니다. 할일은 마감일이 설정되면
                캘린더에도 표시됩니다.
                {selectedDate && (
                  <span style={{ display: 'block', marginTop: '4px', color: 'var(--accent-2)' }}>
                    💡 캘린더에서 날짜를 클릭하면 해당 날짜의 일정만 표시됩니다.
                  </span>
                )}
              </p>
            </div>
            <button
              className="btn primary"
              type="button"
              onClick={() => openTodoModal()}
              style={{ whiteSpace: 'nowrap', flexShrink: 0, alignSelf: 'flex-start' }}
            >
              할일 추가
            </button>
          </div>
          {todos.length === 0 ? (
            <div style={{ textAlign: 'center', color: 'var(--muted)', padding: '40px' }}>할일이 없습니다.</div>
          ) : (
            <div>
              {todos.map((todo) => (
                <div key={todo.id} className={clsx('todo-item', { completed: todo.is_completed })}>
                  <div
                    className={clsx('todo-checkbox', { checked: todo.is_completed })}
                    onClick={(e) => {
                      e.stopPropagation()
                      toggleTodo(todo.id)
                    }}
                  ></div>
                  <div style={{ flex: 1, cursor: 'pointer' }} onClick={() => openTodoModal(todo)}>
                    <div style={{ fontWeight: 600, marginBottom: '4px' }}>{todo.title}</div>
                    {todo.due_date && (
                      <div style={{ fontSize: '12px', color: 'var(--muted)' }}>마감: {todo.due_date}</div>
                    )}
                  </div>
                  <div
                    style={{
                      padding: '4px 8px',
                      borderRadius: '4px',
                      fontSize: '12px',
                      background:
                        todo.priority === 'high'
                          ? 'var(--danger)'
                          : todo.priority === 'medium'
                          ? 'var(--warn)'
                          : 'var(--ok)',
                    }}
                  >
                    {todo.priority === 'high' ? '높음' : todo.priority === 'medium' ? '보통' : '낮음'}
                  </div>
                  <div style={{ display: 'flex', gap: '6px', alignItems: 'center', flexShrink: 0 }}>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation()
                        openTodoModal(todo)
                      }}
                      title="수정"
                      style={{
                        padding: '6px 10px',
                        background: 'var(--soft)',
                        border: '1px solid var(--line)',
                        borderRadius: '6px',
                        color: 'var(--accent-2)',
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '13px',
                        fontWeight: 500,
                        whiteSpace: 'nowrap',
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = 'var(--accent)'
                        e.currentTarget.style.color = '#fff'
                        e.currentTarget.style.borderColor = 'var(--accent)'
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'var(--soft)'
                        e.currentTarget.style.color = 'var(--accent-2)'
                        e.currentTarget.style.borderColor = 'var(--line)'
                      }}
                    >
                      수정
                    </button>
                    <button
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation()
                        deleteTodo(todo.id)
                      }}
                      title="삭제"
                      style={{
                        padding: '6px 10px',
                        background: 'var(--soft)',
                        border: '1px solid var(--line)',
                        borderRadius: '6px',
                        color: 'var(--danger)',
                        cursor: 'pointer',
                        transition: 'all 0.2s',
                        display: 'flex',
                        alignItems: 'center',
                        justifyContent: 'center',
                        fontSize: '13px',
                        fontWeight: 500,
                        whiteSpace: 'nowrap',
                      }}
                      onMouseEnter={(e) => {
                        e.currentTarget.style.background = 'var(--danger)'
                        e.currentTarget.style.color = '#fff'
                        e.currentTarget.style.borderColor = 'var(--danger)'
                      }}
                      onMouseLeave={(e) => {
                        e.currentTarget.style.background = 'var(--soft)'
                        e.currentTarget.style.color = 'var(--danger)'
                        e.currentTarget.style.borderColor = 'var(--line)'
                      }}
                    >
                      삭제
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* 일정 추가 모달 */}
      {showEventModal && (
        <div className="modal-overlay" onClick={(e) => e.target === e.currentTarget && closeEventModal()}>
          <div className="modal-card">
            <h3 style={{ marginTop: 0 }}>{editingEventId ? '일정 수정' : '일정 추가'}</h3>
            <div className="form-group">
              <label>제목</label>
              <input
                value={eventForm.title}
                onChange={(e) => setEventForm({ ...eventForm, title: e.target.value })}
                type="text"
                required
              />
            </div>
            <div className="form-group">
              <label>날짜</label>
              <div className="input-with-icon">
                <input
                  value={eventForm.start_date}
                  onChange={(e) => handleDateInput(e, 'start_date')}
                  onKeyDown={(e) => handleDateKeydown(e, 'start_date')}
                  onPaste={(e) => handleDatePaste(e, 'start_date')}
                  type="text"
                  required
                  placeholder="YYYY-MM-DD"
                  maxLength={10}
                />
                <span className="input-icon">📅</span>
              </div>
            </div>
            <div className="form-group">
              <label>시간</label>
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <div style={{ display: 'flex', gap: '4px', alignItems: 'center', flex: 1 }}>
                  <input
                    value={eventForm.timeHour}
                    onChange={handleTimeHourChange}
                    type="text"
                    placeholder="시"
                    maxLength={2}
                    style={{ width: '60px', textAlign: 'center' }}
                  />
                  <span style={{ color: 'var(--muted)' }}>:</span>
                  <input
                    value={eventForm.timeMinute}
                    onChange={handleTimeMinuteChange}
                    type="text"
                    placeholder="분"
                    maxLength={2}
                    style={{ width: '60px', textAlign: 'center' }}
                  />
                </div>
                <div style={{ display: 'flex', gap: '4px' }}>
                  <button
                    type="button"
                    className={clsx('btn', { primary: eventForm.timePeriod === 'AM' })}
                    style={{ padding: '8px 16px', minWidth: '60px' }}
                    onClick={() => setEventForm({ ...eventForm, timePeriod: 'AM' })}
                  >
                    오전
                  </button>
                  <button
                    type="button"
                    className={clsx('btn', { primary: eventForm.timePeriod === 'PM' })}
                    style={{ padding: '8px 16px', minWidth: '60px' }}
                    onClick={() => setEventForm({ ...eventForm, timePeriod: 'PM' })}
                  >
                    오후
                  </button>
                </div>
              </div>
            </div>
            <div className="form-group">
              <label>카테고리</label>
              <select
                value={eventForm.category}
                onChange={(e) => setEventForm({ ...eventForm, category: e.target.value })}
              >
                <option value="general">일반</option>
                <option value="todo">할일</option>
                <option value="payment">결제</option>
                <option value="meeting">미팅</option>
                <option value="fitting">피팅</option>
                <option value="booking">예약</option>
                <option value="preparation">준비</option>
              </select>
            </div>
            <div className="form-group">
              <label>우선순위</label>
              <select
                value={eventForm.priority}
                onChange={(e) => setEventForm({ ...eventForm, priority: e.target.value as 'low' | 'medium' | 'high' })}
              >
                <option value="low">낮음</option>
                <option value="medium">보통</option>
                <option value="high">높음</option>
              </select>
            </div>
            <div className="form-group">
              <label>담당자</label>
              <select
                value={eventForm.assignee}
                onChange={(e) => setEventForm({ ...eventForm, assignee: e.target.value })}
              >
                <option value="both">공동</option>
                <option value="groom">신랑</option>
                <option value="bride">신부</option>
              </select>
            </div>
            <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end', marginTop: '20px' }}>
              <button className="btn" type="button" onClick={closeEventModal}>
                취소
              </button>
              {editingEventId && (
                <button className="btn danger" type="button" onClick={() => deleteEvent(editingEventId!)}>
                  삭제
                </button>
              )}
              <button className="btn primary" type="button" onClick={createEvent}>
                {editingEventId ? '수정' : '추가'}
              </button>
            </div>
          </div>
        </div>
      )}
    </section>
  )
}
