<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import { useApi } from '@/composables/useApi'

interface CalendarEvent {
  id: number
  title: string
  start_date: string
  start_time?: string | null
  end_date?: string | null
  end_time?: string | null
  category: string
  priority: 'low' | 'medium' | 'high'
  assignee?: string | null
  description?: string | null
      is_completed?: boolean
      // is_auto_generated는 DB에 없으므로 제거
    }

interface Todo {
  id: number
  title: string
  due_date?: string | null
  priority: 'low' | 'medium' | 'high'
  assignee?: string | null
  description?: string | null
  is_completed: boolean
}

const authStore = useAuthStore()
const { request } = useApi()

const currentDate = ref(new Date())
const events = ref<CalendarEvent[]>([])
const todos = ref<Todo[]>([])
const weddingDate = ref<string | null>(null)
const dDay = ref<number | null>(null)
const showAutoGeneratedEvents = ref(true) // 자동 생성된 일정 표시 여부
// 오늘 날짜를 기본 선택값으로 설정
const today = new Date()
const todayStr = `${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
const selectedDate = ref<string | null>(todayStr) // 선택된 날짜 (할일 리스트 필터링용) - 기본값: 오늘

const ASSIGNEE_COLORS = {
  groom: {
    background: '#3b82f6',
    border: 'rgba(59, 130, 246, 0.4)',
    shadow: 'rgba(59, 130, 246, 0.35)',
  },
  bride: {
    background: '#ec4899',
    border: 'rgba(236, 72, 153, 0.4)',
    shadow: 'rgba(236, 72, 153, 0.35)',
  },
  both: {
    background: '#8b5cf6',
    border: 'rgba(139, 92, 246, 0.4)',
    shadow: 'rgba(139, 92, 246, 0.35)',
  },
} as const

const showEventModal = ref(false)
const editingEventId = ref<number | null>(null)

const eventForm = ref({
  title: '',
  start_date: new Date().toISOString().split('T')[0],
  start_time: '',
  timeHour: '',
  timeMinute: '',
  timePeriod: 'AM' as 'AM' | 'PM',
  category: 'general',
  priority: 'medium' as 'low' | 'medium' | 'high',
  assignee: 'both',
  description: '',
})

const todoForm = ref({
  title: '',
  due_date: '',
  priority: 'medium' as 'low' | 'medium' | 'high',
  assignee: 'both',
  description: '',
  show_in_calendar: false, // 캘린더에 표시 여부
})

const currentMonthText = computed(() => {
  const year = currentDate.value.getFullYear()
  const month = currentDate.value.getMonth() + 1
  return `${year}년 ${month}월`
})

const calendarDays = computed(() => {
  const year = currentDate.value.getFullYear()
  const month = currentDate.value.getMonth()
  const firstDay = new Date(year, month, 1)
  const lastDay = new Date(year, month + 1, 0)
  const startDate = new Date(firstDay)
  startDate.setDate(startDate.getDate() - startDate.getDay())

  const days: Array<{
    date: Date
    isCurrentMonth: boolean
    isToday: boolean
    events: CalendarEvent[]
  }> = []

  for (let i = 0; i < 42; i++) {
    const date = new Date(startDate)
    date.setDate(startDate.getDate() + i)
    // 타임존 변환 없이 로컬 날짜로 직접 포맷팅
    const year = date.getFullYear()
    const month = String(date.getMonth() + 1).padStart(2, '0')
    const day = String(date.getDate()).padStart(2, '0')
    const dateStr = `${year}-${month}-${day}`
    
    let dayEvents = events.value.filter((e) => e.start_date === dateStr)
    
    // 할일은 이제 일정으로 통합되었으므로 별도 처리 불필요
    
    // 예식일이 설정되어 있고 해당 날짜면 예식일 일정 추가
    if (weddingDate.value && weddingDate.value === dateStr) {
      const hasWeddingEvent = dayEvents.some((e) => e.title.includes('예식일') || e.category === 'wedding')
      if (!hasWeddingEvent) {
        dayEvents = [
          ...dayEvents,
          {
            id: -1, // 임시 ID (예식일 표시용)
            title: '예식일',
            start_date: dateStr,
            category: 'wedding',
            priority: 'high' as const,
            assignee: 'both',
            description: '예식일',
          } as CalendarEvent,
        ]
      }
    }
    
        // 자동 생성된 일정 필터링은 DB에 is_auto_generated 컬럼이 없으므로 제거
        // 필요시 다른 방법으로 필터링 가능
    
    const isToday =
      date.toDateString() === new Date().toDateString()

    days.push({
      date,
      isCurrentMonth: date.getMonth() === month,
      isToday,
      events: dayEvents,
    })
  }

  return days
})

const canAccess = computed(() => authStore.isAuthenticated)

// 로그인 상태 변경 감지 - 사용자 ID 변경 시
watch(
  () => authStore.user?.id,
  (newUserId, oldUserId) => {
    console.log('watch user.id:', { newUserId, oldUserId, isAuthenticated: authStore.isAuthenticated })
    
    // 로그아웃 시 데이터 초기화
    if (!newUserId && oldUserId) {
      console.log('로그아웃 감지 - 데이터 초기화')
      events.value = []
      todos.value = []
      weddingDate.value = null
      dDay.value = null
      return
    }
    
    // 로그인 시 또는 사용자 변경 시 데이터 로드
    if (newUserId && newUserId !== oldUserId) {
      console.log('사용자 ID 변경 감지 - 데이터 로드 예정:', { oldUserId, newUserId })
      // nextTick을 사용하여 Vue의 반응성 업데이트가 완료된 후 실행
      nextTick(() => {
        if (authStore.user?.id === newUserId && authStore.isAuthenticated) {
          console.log('사용자 ID 변경 후 데이터 로드 실행')
          loadData()
        } else {
          console.warn('사용자 ID 변경 후 조건 불일치:', {
            currentUserId: authStore.user?.id,
            expectedUserId: newUserId,
            isAuthenticated: authStore.isAuthenticated
          })
        }
      })
    }
  },
  { immediate: false }
)

// 인증 상태 변경 감지
watch(
  () => authStore.isAuthenticated,
  (isAuth, wasAuth) => {
    console.log('watch isAuthenticated:', { isAuth, wasAuth, userId: authStore.user?.id })
    
    if (!isAuth && wasAuth) {
      // 로그아웃 시 모든 데이터 초기화
      console.log('로그아웃 감지 - 데이터 초기화')
      events.value = []
      todos.value = []
      weddingDate.value = null
      dDay.value = null
    } else if (isAuth && !wasAuth) {
      // 로그인 시 데이터 로드 (이전에 로그인하지 않았을 때만)
      const userId = authStore.user?.id
      console.log('로그인 감지 - 데이터 로드 예정:', { userId })
      
      if (userId) {
        // nextTick을 사용하여 Vue의 반응성 업데이트가 완료된 후 실행
        nextTick(() => {
          if (authStore.isAuthenticated && authStore.user?.id === userId) {
            console.log('로그인 후 데이터 로드 실행')
            loadData()
          } else {
            console.warn('로그인 후 조건 불일치:', {
              isAuthenticated: authStore.isAuthenticated,
              userId: authStore.user?.id,
              expectedUserId: userId
            })
          }
        })
      } else {
        console.warn('로그인 감지되었지만 사용자 ID가 없습니다.')
      }
    }
  }
)

onMounted(() => {
  console.log('CalendarView onMounted:', {
    isAuthenticated: authStore.isAuthenticated,
    userId: authStore.user?.id,
    canAccess: canAccess.value
  })
  
  if (!canAccess.value) {
    authStore.openLoginModal()
    return
  }
  
  // 로그인 상태면 데이터 로드
  if (authStore.user?.id) {
    console.log('onMounted: 사용자 ID가 있으므로 데이터 로드 시작')
    loadData()
  } else {
    console.warn('onMounted: 사용자 ID가 없습니다. 로그인 모달을 엽니다.')
  }
})

async function loadData() {
  const userId = authStore.user?.id
  if (!userId) {
    console.warn('loadData: 사용자 ID가 없어서 데이터를 로드할 수 없습니다.')
    return
  }
  
  console.log('loadData: 데이터 로드 시작, user_id:', userId)
  try {
    await Promise.all([loadEvents(), loadWeddingDate()])
    updateDDay()
    // 할일은 일정 로드 후에 로드 (일정 데이터를 사용하므로)
    await loadTodos()
    console.log('loadData: 모든 데이터 로드 완료', {
      eventsCount: events.value.length,
      todosCount: todos.value.length,
      weddingDate: weddingDate.value,
      selectedDate: selectedDate.value
    })
  } catch (err) {
    console.error('loadData: 데이터 로드 중 오류 발생:', err)
  }
}

async function loadWeddingDate() {
  if (!authStore.user?.id) {
    weddingDate.value = null
    dDay.value = null
    console.log('loadWeddingDate: 사용자 ID 없음')
    return
  }
  
  try {
    console.log('loadWeddingDate: 예식일 조회 시작, user_id:', authStore.user.id)
    const res = await request<{ message: string; data: { wedding_date: string | null } }>(
      `/calendar/wedding-date`,
      { method: 'GET' }
    )
    console.log('loadWeddingDate: 응답 받음:', JSON.stringify(res, null, 2))
    
    // 응답 형식 확인
    if (res && typeof res === 'object') {
      if ('message' in res && res.message === 'wedding_date_retrieved') {
        if (res.data && res.data.wedding_date) {
          weddingDate.value = res.data.wedding_date
          console.log('loadWeddingDate: 예식일 로드 성공:', weddingDate.value)
          updateDDay()
        } else {
          weddingDate.value = null
          console.log('loadWeddingDate: 예식일 없음 (data.wedding_date가 null)')
        }
      } else {
        console.warn('loadWeddingDate: 예상치 못한 응답 형식:', res)
        weddingDate.value = null
      }
    } else {
      console.error('loadWeddingDate: 응답이 객체가 아님:', res)
      weddingDate.value = null
    }
  } catch (err: any) {
    console.error('예식일 로드 실패:', err)
    console.error('예식일 로드 실패 상세:', {
      message: err?.message,
      data: err?.data,
      response: err?.response,
      status: err?.status
    })
    weddingDate.value = null
    dDay.value = null
  }
}

function updateDDay() {
  if (!weddingDate.value) {
    dDay.value = null
    return
  }
  
  // 타임존 변환 없이 날짜만 비교
  const [year, month, day] = weddingDate.value.split('-').map(Number)
  const wedding = new Date(year, month - 1, day)
  wedding.setHours(0, 0, 0, 0)
  
  const today = new Date()
  today.setHours(0, 0, 0, 0)
  
  const diff = Math.ceil((wedding.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
  dDay.value = diff
}

async function setWeddingDate() {
  const date = weddingDate.value
  if (!date || !date.match(/^\d{4}-\d{2}-\d{2}$/)) {
    alert('올바른 날짜 형식(YYYY-MM-DD)을 입력해주세요.')
    return
  }

  // 날짜 유효성 검증 (타임존 변환 없이 직접 파싱)
  const [year, month, day] = date.split('-').map(Number)
  const dateObj = new Date(year, month - 1, day)
  if (
    dateObj.getFullYear() !== year ||
    dateObj.getMonth() !== month - 1 ||
    dateObj.getDate() !== day
  ) {
    alert('유효하지 않은 날짜입니다.')
    return
  }

  try {
    console.log('예식일 설정 요청 (입력값):', date, 'user_id:', authStore.user!.id)
    
    const res = await request<{ message: string; data: { wedding_date: string } }>(
      `/calendar/wedding-date`,
      {
        method: 'POST',
        body: { wedding_date: date },
      }
    )
    
    console.log('예식일 설정 응답:', res)
    
    // 예식일 설정 후 즉시 업데이트
    if (res.message === 'wedding_date_set' && res.data?.wedding_date) {
      // 응답에서 받은 날짜를 그대로 사용 (입력한 날짜 그대로)
      const savedDate = res.data.wedding_date
      weddingDate.value = savedDate
      updateDDay()
      
      // 캘린더를 예식일이 있는 월로 이동 (타임존 변환 없이 직접 파싱)
      const [savedYear, savedMonth] = savedDate.split('-').map(Number)
      currentDate.value = new Date(savedYear, savedMonth - 1, 1)
      
      // 날짜 포맷팅 (2025년 11월 25일) - 저장된 날짜에서 직접 파싱
      const [displayYear, displayMonth, displayDay] = savedDate.split('-').map(Number)
      const formattedDate = `${displayYear}년 ${displayMonth}월 ${displayDay}일`
      
      console.log('설정된 예식일:', savedDate, '표시:', formattedDate)
      
      // 간단한 확인 메시지
      alert(`예식일이 ${formattedDate}로 설정되었습니다.\n\n"타임라인 자동 생성" 버튼을 눌러 일정을 생성할 수 있습니다.`)
    } else {
      console.error('예식일 설정 응답 형식 오류:', res)
      throw new Error('예식일 설정 응답이 올바르지 않습니다.')
    }
  } catch (err: any) {
    console.error('예식일 설정 실패:', err)
    console.error('예식일 설정 실패 상세:', {
      message: err?.message,
      data: err?.data,
      response: err?.response,
      stack: err?.stack
    })
    const errorMessage = err?.data?.message || err?.message || '알 수 없는 오류'
    alert(`예식일 설정에 실패했습니다.\n오류: ${errorMessage}`)
  }
}

async function generateTimeline() {
  // 예식일 확인 - weddingDate.value가 없으면 DB에서 다시 로드 시도
  let targetDate = weddingDate.value
  if (!targetDate) {
    try {
      const res = await request<{ data: { wedding_date: string | null } }>(
        `/calendar/wedding-date`,
        { method: 'GET' }
      )
      if (res.data?.wedding_date) {
        targetDate = res.data.wedding_date
        weddingDate.value = targetDate
      } else {
        alert('예식일을 먼저 설정해주세요.')
        return
      }
    } catch (err) {
      console.error('예식일 로드 실패:', err)
      alert('예식일을 먼저 설정해주세요.')
      return
    }
  }

  // 기존 일정이 있으면 확인
  if (events.value.length > 0) {
    if (!confirm('기존 일정을 모두 삭제하고 새 타임라인을 생성하시겠습니까?')) return
  }

  try {
    const response = await request(`/calendar/timeline/generate`, {
      method: 'POST',
      body: {
        wedding_date: targetDate,
        user_preferences: {},
      },
    })
    
    // 응답 확인
    if (response.message === 'timeline_generated' || response.message === 'timeline_created') {
      alert('타임라인이 생성되었습니다.')
      await loadData()
    } else {
      throw new Error('타임라인 생성 응답이 올바르지 않습니다.')
    }
  } catch (err: any) {
    console.error('타임라인 생성 실패:', err)
    const errorMessage = err?.data?.message || err?.message || '알 수 없는 오류'
    alert(`타임라인 생성에 실패했습니다.\n오류: ${errorMessage}`)
  }
}

    async function loadEvents() {
      const userId = authStore.user?.id
      if (!userId) {
        console.log('loadEvents: 사용자 ID가 없어서 일정을 로드하지 않습니다.')
        events.value = []
        return
      }
      
      try {
        console.log('loadEvents: 일정 로드 시작, user_id:', userId)
        const res = await request<{ message: string; data: { events: CalendarEvent[] } }>(
          `/calendar/todos`,
          { method: 'GET' }
        )
        if (res.message === 'todos_retrieved') {
          events.value = res.data.events || []
          console.log('loadEvents: 일정 로드 완료, 개수:', events.value.length)
        } else {
          console.warn('loadEvents: 예상하지 못한 응답:', res.message)
          events.value = []
        }
      } catch (err) {
        console.error('일정 로드 실패:', err)
        events.value = []
      }
    }

async function loadTodos() {
  const userId = authStore.user?.id
  if (!userId) {
    console.log('loadTodos: 사용자 ID가 없어서 할일을 로드하지 않습니다.')
    todos.value = []
    return
  }
  
  try {
    console.log('loadTodos: 할일 로드 시작, user_id:', userId, '선택된 날짜:', selectedDate.value)
    
    // 선택된 날짜가 있으면 해당 날짜의 모든 일정을 표시
    if (selectedDate.value) {
      // 선택된 날짜의 일정만 필터링
      const dayEvents = events.value.filter((e) => e.start_date === selectedDate.value)
      todos.value = dayEvents.map((event) => ({
        id: event.id,
        title: event.title,
        due_date: event.start_date,
        priority: event.priority,
        assignee: event.assignee || 'both',
        description: event.description || null,
        is_completed: event.is_completed || false,
      }))
      console.log('loadTodos: 선택된 날짜의 일정 로드 완료, 개수:', todos.value.length)
    } else {
      // 선택된 날짜가 없으면 category가 'todo'인 일정만 표시
      const todoEvents = events.value.filter((e) => e.category === 'todo')
      todos.value = todoEvents.map((event) => ({
        id: event.id,
        title: event.title,
        due_date: event.start_date,
        priority: event.priority,
        assignee: event.assignee || 'both',
        description: event.description || null,
        is_completed: event.is_completed || false,
      }))
      console.log('loadTodos: 할일 로드 완료, 개수:', todos.value.length)
    }
  } catch (err) {
    console.error('할일 로드 실패:', err)
    todos.value = []
  }
}

// 날짜 클릭 핸들러
function handleDateClick(dateStr: string) {
  if (selectedDate.value === dateStr) {
    // 같은 날짜를 다시 클릭하면 선택 해제
    selectedDate.value = null
  } else {
    // 다른 날짜 클릭 시 선택
    selectedDate.value = dateStr
  }
  // 할일 리스트 새로고침
  loadTodos()
}

function prevMonth() {
  currentDate.value = new Date(currentDate.value.getFullYear(), currentDate.value.getMonth() - 1, 1)
}

function nextMonth() {
  currentDate.value = new Date(currentDate.value.getFullYear(), currentDate.value.getMonth() + 1, 1)
}

function parseTimeTo12Hour(time24: string | null | undefined): { hour: string; minute: string; period: 'AM' | 'PM' } {
  if (!time24) {
    return { hour: '', minute: '', period: 'AM' }
  }
  const [hour, minute] = time24.split(':')
  const hourNum = parseInt(hour, 10)
  if (hourNum === 0) {
    return { hour: '12', minute: minute || '', period: 'AM' }
  } else if (hourNum < 12) {
    return { hour: hour, minute: minute || '', period: 'AM' }
  } else if (hourNum === 12) {
    return { hour: '12', minute: minute || '', period: 'PM' }
  } else {
    return { hour: String(hourNum - 12), minute: minute || '', period: 'PM' }
  }
}

function formatTimeTo24Hour(hour: string, minute: string, period: 'AM' | 'PM'): string {
  if (!hour || !minute) return ''
  let hourNum = parseInt(hour, 10)
  if (isNaN(hourNum) || hourNum < 1 || hourNum > 12) return ''
  if (period === 'PM' && hourNum !== 12) {
    hourNum += 12
  } else if (period === 'AM' && hourNum === 12) {
    hourNum = 0
  }
  const minuteNum = parseInt(minute, 10)
  if (isNaN(minuteNum) || minuteNum < 0 || minuteNum > 59) return ''
  return `${String(hourNum).padStart(2, '0')}:${String(minuteNum).padStart(2, '0')}`
}

function openEventModal(event?: CalendarEvent) {
  if (event) {
    editingEventId.value = event.id
    const timeParts = parseTimeTo12Hour(event.start_time)
    eventForm.value = {
      title: event.title,
      start_date: event.start_date,
      start_time: event.start_time || '',
      timeHour: timeParts.hour,
      timeMinute: timeParts.minute,
      timePeriod: timeParts.period,
      category: event.category || 'general',
      priority: event.priority,
      assignee: event.assignee || 'both',
      description: event.description || '',
    }
  } else {
    editingEventId.value = null
    eventForm.value = {
      title: '',
      start_date: new Date().toISOString().split('T')[0],
      start_time: '',
      timeHour: '',
      timeMinute: '',
      timePeriod: 'AM',
      category: 'general',
      priority: 'medium',
      assignee: 'both',
      description: '',
    }
  }
  showEventModal.value = true
}

function closeEventModal() {
  showEventModal.value = false
  editingEventId.value = null
}

function openTodoModal(todo?: Todo) {
  // 할일도 일정으로 통합 - 일정 모달 열기
  if (todo) {
    // 할일을 일정으로 변환하여 수정 모달 열기
    const event: CalendarEvent = {
      id: todo.id,
      title: todo.title,
      start_date: todo.due_date || new Date().toISOString().split('T')[0],
      start_time: null,
      end_date: null,
      end_time: null,
      category: 'todo',
      priority: todo.priority,
      assignee: todo.assignee || 'both',
      description: todo.description || null,
      is_completed: todo.is_completed,
    }
    openEventModal(event)
  } else {
    // 새 할일 추가 - 일정 모달 열기 (category: 'todo')
    editingEventId.value = null
    eventForm.value = {
      title: '',
      start_date: new Date().toISOString().split('T')[0],
      start_time: '',
      timeHour: '',
      timeMinute: '',
      timePeriod: 'AM',
      category: 'todo', // 할일은 category를 'todo'로 설정
      priority: 'medium',
      assignee: 'both',
      description: '',
    }
    showEventModal.value = true
  }
}

// closeTodoModal 함수는 더 이상 사용하지 않음 - closeEventModal로 통합됨

async function createEvent() {
  if (!eventForm.value.title || !eventForm.value.start_date) {
    alert('제목과 날짜를 입력해주세요.')
    return
  }

  try {
    // 시간 포맷팅 (12시간 형식 -> 24시간 형식)
    const time24 = formatTimeTo24Hour(
      eventForm.value.timeHour,
      eventForm.value.timeMinute,
      eventForm.value.timePeriod
    )

    if (editingEventId.value) {
      // 수정
      await request(`/calendar/todos/${editingEventId.value}`, {
        method: 'PUT',
        body: {
          title: eventForm.value.title,
          start_date: eventForm.value.start_date,
          start_time: time24 || null,
          category: eventForm.value.category,
          priority: eventForm.value.priority,
          assignee: eventForm.value.assignee,
          description: eventForm.value.description || null,
          is_completed: eventForm.value.is_completed,
        },
      })
      alert('일정이 수정되었습니다.')
    } else {
      // 생성
      await request(`/calendar/todos`, {
        method: 'POST',
        body: {
          title: eventForm.value.title,
          start_date: eventForm.value.start_date,
          start_time: time24 || null,
          category: eventForm.value.category,
          priority: eventForm.value.priority,
          assignee: eventForm.value.assignee,
          description: eventForm.value.description || null,
          is_completed: eventForm.value.is_completed,
        },
      })
      alert('일정이 추가되었습니다.')
    }
    closeEventModal()
    await loadData()
  } catch (err) {
    console.error(err)
    alert(editingEventId.value ? '일정 수정에 실패했습니다.' : '일정 추가에 실패했습니다.')
  }
}

async function deleteEvent(eventId: number) {
  if (!confirm('정말 이 일정을 삭제하시겠습니까?')) return

  try {
    await request(`/calendar/todos/${eventId}`, {
      method: 'DELETE',
    })
    // 모달 즉시 닫기
    closeEventModal()
    await loadData()
    alert('일정이 삭제되었습니다.')
  } catch (err) {
    console.error(err)
    alert('일정 삭제에 실패했습니다.')
  }
}

// createTodo 함수는 더 이상 사용하지 않음 - createEvent로 통합됨

async function deleteTodo(todoId: number) {
  if (!confirm('정말 이 할일을 삭제하시겠습니까?')) return

  try {
    // 할일도 일정으로 통합되었으므로 todos API 사용
    await request(`/calendar/todos/${todoId}`, {
      method: 'DELETE',
    })
    // 할일 리스트 새로고침
    await loadData()
    // 캘린더도 업데이트
    await loadEvents()
    alert('할일이 삭제되었습니다.')
  } catch (err) {
    console.error('할일 삭제 오류:', err)
    alert('할일 삭제에 실패했습니다.')
  }
}

async function toggleTodo(todoId: number) {
  const todo = todos.value.find((t) => t.id === todoId)
  if (!todo) return

  try {
    // 할일도 일정으로 통합되었으므로 todos API 사용
    await request(`/calendar/todos/${todoId}`, {
      method: 'PUT',
      body: {
        is_completed: !todo.is_completed,
      },
    })
    // 할일 리스트 새로고침
    await loadTodos()
    // 캘린더도 업데이트
    await loadEvents()
  } catch (err) {
    console.error('할일 상태 변경 오류:', err)
    alert('할일 상태 변경에 실패했습니다.')
  }
}

function getPriorityClass(priority: string) {
  return priority === 'high' ? 'high' : priority === 'medium' ? 'medium' : 'low'
}

function getAssigneeClass(assignee: string | null | undefined) {
  if (assignee === 'groom') return 'assignee-groom'
  if (assignee === 'bride') return 'assignee-bride'
  return 'assignee-both'
}

function getEventStyle(event: CalendarEvent) {
  // 예식일은 기존 스타일 유지
  if (event.category === 'wedding' || event.id === -1) {
    return {}
  }

  // 할일은 다른 스타일 적용
  if (event.category === 'todo' || event.id < -1000) {
    const colors =
      ASSIGNEE_COLORS[(event.assignee as keyof typeof ASSIGNEE_COLORS) || 'both'] ||
      ASSIGNEE_COLORS.both
    return {
      background: `linear-gradient(135deg, ${colors.background}dd, ${colors.background}aa)`,
      backgroundColor: `${colors.background}dd`,
      borderColor: colors.border,
      boxShadow: `0 1px 3px ${colors.shadow}`,
      borderStyle: 'dashed',
      borderWidth: '1px',
    }
  }

  const colors =
    ASSIGNEE_COLORS[(event.assignee as keyof typeof ASSIGNEE_COLORS) || 'both'] ||
    ASSIGNEE_COLORS.both

  return {
    background: colors.background,
    backgroundColor: colors.background,
    borderColor: colors.border,
    boxShadow: `0 2px 6px ${colors.shadow}`,
  }
}

function handleEventClick(event: CalendarEvent) {
  // 예식일은 클릭 불가
  if (event.id === -1) {
    return
  }
  
  // 할일 클릭 (ID가 -1000 미만인 경우)
  if (event.id < -1000) {
    const todoId = -event.id - 1000
    const todo = todos.value.find((t) => t.id === todoId)
    if (todo) {
      openTodoModal(todo)
    }
    return
  }
  
  // 일반 일정 클릭
  openEventModal(event)
}

function handleDateKeydown(event: KeyboardEvent, field: 'start_date' | 'due_date' | 'wedding_date') {
  const input = event.target as HTMLInputElement
  
  // 백스페이스, 삭제, 화살표 키 등은 허용
  if (['Backspace', 'Delete', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Tab', 'Enter'].includes(event.key)) {
    return
  }
  
  // Ctrl/Cmd + A, C, V, X 등은 허용
  if (event.ctrlKey || event.metaKey) {
    return
  }
  
  // 숫자만 허용
  if (!/^\d$/.test(event.key)) {
    event.preventDefault()
    return
  }
  
  const currentValue = input.value.replace(/\D/g, '') // 숫자만 추출
  const newValue = currentValue + event.key
  
  // 최대 8자리까지만 허용
  if (newValue.length > 8) {
    event.preventDefault()
    return
  }
  
  // YYYY-MM-DD 형식으로 자동 포맷팅
  let formatted = newValue
  if (newValue.length > 4) {
    formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6)
  }
  if (newValue.length > 6) {
    formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6) + '-' + newValue.slice(6, 8)
  }
  
  // 연도 4자리 입력 완료 시 자동으로 하이픈 추가하고 월 필드로 포커스 이동
  if (newValue.length === 4) {
    event.preventDefault()
    formatted = newValue + '-'
    updateDateValue(field, formatted)
    nextTick(() => {
      input.value = formatted
      const position = 5 // YYYY-|MM-DD
      input.setSelectionRange(position, position)
    })
    return
  }
  
  // 월 2자리 입력 완료 시 자동으로 하이픈 추가하고 일 필드로 포커스 이동
  if (newValue.length === 6) {
    event.preventDefault()
    formatted = newValue.slice(0, 4) + '-' + newValue.slice(4, 6) + '-'
    updateDateValue(field, formatted)
    nextTick(() => {
      input.value = formatted
      const position = formatted.length // YYYY-MM-|DD
      input.setSelectionRange(position, position)
    })
    return
  }
  
  // 일반 입력 시 포맷팅만 적용
  event.preventDefault()
  formatted = formatDateValue(newValue)
  updateDateValue(field, formatted)
  nextTick(() => {
    input.value = formatted
    const position = formatted.length
    input.setSelectionRange(position, position)
  })
}

function formatDateValue(digits: string): string {
  if (digits.length <= 4) {
    return digits
  } else if (digits.length <= 6) {
    return digits.slice(0, 4) + '-' + digits.slice(4, 6)
  } else {
    return digits.slice(0, 4) + '-' + digits.slice(4, 6) + '-' + digits.slice(6, 8)
  }
}

function updateDateValue(field: 'start_date' | 'due_date' | 'wedding_date', value: string) {
  if (field === 'start_date') {
    eventForm.value.start_date = value
  } else if (field === 'due_date') {
    todoForm.value.due_date = value
  } else if (field === 'wedding_date') {
    weddingDate.value = value
  }
}

function handleDateInput(event: Event, field: 'start_date' | 'due_date' | 'wedding_date') {
  const input = event.target as HTMLInputElement
  const value = input.value
  
  // 이미 올바른 형식이면 그대로 사용
  if (value.match(/^\d{4}-\d{2}-\d{2}$/)) {
    updateDateValue(field, value)
    return
  }
  
  // 숫자만 추출하여 포맷팅
  const digits = value.replace(/\D/g, '').slice(0, 8)
  const formatted = formatDateValue(digits)
  updateDateValue(field, formatted)
  
  nextTick(() => {
    if (input.value !== formatted) {
      input.value = formatted
    }
  })
}

function handleDatePaste(event: ClipboardEvent, field: 'start_date' | 'due_date' | 'wedding_date') {
  event.preventDefault()
  const input = event.target as HTMLInputElement
  const pastedText = event.clipboardData?.getData('text') || ''
  const digits = pastedText.replace(/\D/g, '').slice(0, 8)
  const formatted = formatDateValue(digits)
  
  updateDateValue(field, formatted)
  
  nextTick(() => {
    input.value = formatted
    input.setSelectionRange(formatted.length, formatted.length)
  })
}
</script>

<template>
  <section class="section" id="calendar">
    <div class="container" style="display: flex; flex-direction: column; gap: 20px">
      <div class="page-title">
        <h1>📅 개인화 일정 관리(캘린더)</h1>
        <p>D-Day 기반 타임라인 자동 생성 + Todo 리스트</p>
      </div>

      <!-- 예식일 설정 -->
      <div class="card">
        <div class="wedding-date-section">
          <label style="font-weight: 600">예식일:</label>
          <input
            type="text"
            id="weddingDateInput"
            :value="weddingDate || ''"
            placeholder="YYYY-MM-DD"
            maxlength="10"
            @keydown="handleDateKeydown($event, 'wedding_date')"
            @input="handleDateInput($event, 'wedding_date')"
            @paste="handleDatePaste($event, 'wedding_date')"
          />
          <button class="btn primary" type="button" @click="setWeddingDate">설정</button>
          <button class="btn" type="button" @click="generateTimeline">타임라인 자동 생성</button>
          <label style="display: flex; align-items: center; gap: 8px; margin-left: 12px; cursor: pointer;">
            <input
              type="checkbox"
              v-model="showAutoGeneratedEvents"
              style="width: 18px; height: 18px; cursor: pointer;"
            />
            <span style="font-size: 14px; color: var(--text)">자동 생성 일정 표시</span>
          </label>
        </div>
        <div v-if="dDay !== null" style="font-size: 18px; font-weight: 600; color: var(--accent); margin-top: 12px">
          <span v-if="dDay > 0">D-{{ dDay }}</span>
          <span v-else-if="dDay === 0">D-Day!</span>
          <span v-else>D+{{ Math.abs(dDay) }}</span>
        </div>
      </div>

      <!-- 캘린더 -->
      <div class="card">
        <div class="calendar-header">
          <h2 style="margin: 0">캘린더</h2>
          <div class="calendar-controls">
            <div class="month-navigation">
              <button class="btn month-btn" type="button" @click="prevMonth">◀</button>
              <span class="month-text">{{ currentMonthText }}</span>
              <button class="btn month-btn" type="button" @click="nextMonth">▶</button>
            </div>
            <button class="btn primary" type="button" @click="openEventModal">일정 추가</button>
          </div>
        </div>
        <!-- 일정 색상 범례 -->
        <div style="display: flex; gap: 16px; margin-bottom: 16px; padding: 12px; background: var(--soft); border-radius: 8px; flex-wrap: wrap">
          <div style="display: flex; align-items: center; gap: 8px">
            <div style="width: 16px; height: 16px; border-radius: 4px; background: #3b82f6"></div>
            <span style="font-size: 13px; color: var(--text)">신랑 일정</span>
          </div>
          <div style="display: flex; align-items: center; gap: 8px">
            <div style="width: 16px; height: 16px; border-radius: 4px; background: #ec4899"></div>
            <span style="font-size: 13px; color: var(--text)">신부 일정</span>
          </div>
          <div style="display: flex; align-items: center; gap: 8px">
            <div style="width: 16px; height: 16px; border-radius: 4px; background: #8b5cf6"></div>
            <span style="font-size: 13px; color: var(--text)">공동 일정</span>
          </div>
          <div style="display: flex; align-items: center; gap: 8px">
            <div style="width: 16px; height: 16px; border-radius: 4px; background: linear-gradient(135deg, var(--accent), var(--accent-2))"></div>
            <span style="font-size: 13px; color: var(--text)">예식일</span>
          </div>
        </div>
        <div class="calendar-grid">
          <div
            v-for="dayName in ['일', '월', '화', '수', '목', '금', '토']"
            :key="dayName"
            style="text-align: center; font-weight: 600; padding: 8px"
          >
            {{ dayName }}
          </div>
          <div
            v-for="(day, idx) in calendarDays"
            :key="idx"
            class="calendar-day"
            :class="{
              'other-month': !day.isCurrentMonth,
              today: day.isToday,
              'selected-date': selectedDate === `${day.date.getFullYear()}-${String(day.date.getMonth() + 1).padStart(2, '0')}-${String(day.date.getDate()).padStart(2, '0')}`
            }"
            @click="handleDateClick(`${day.date.getFullYear()}-${String(day.date.getMonth() + 1).padStart(2, '0')}-${String(day.date.getDate()).padStart(2, '0')}`)"
          >
            <div class="day-number">{{ day.date.getDate() }}</div>
            <div
              v-for="event in day.events"
              :key="`${event.id}-${event.start_date}`"
              class="event-item"
              :class="[
                getPriorityClass(event.priority),
                getAssigneeClass(event.assignee),
                { 
                  'wedding-event': event.category === 'wedding' || event.id === -1,
                  'todo-event': event.category === 'todo' || event.id < -1000
                }
              ]"
              :style="getEventStyle(event)"
              :title="event.description || event.title"
              @click.stop="handleEventClick(event)"
            >
              {{ event.title }}
            </div>
          </div>
        </div>
      </div>

      <!-- Todo 리스트 -->
      <div class="card todo-section">
        <div style="display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 16px; gap: 16px">
          <div style="flex: 1; min-width: 0;">
            <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
              <h2 style="margin: 0">할일 리스트</h2>
              <span v-if="selectedDate" style="font-size: 14px; color: var(--accent-2); font-weight: 600;">
                ({{ selectedDate }})
              </span>
              <button
                v-if="selectedDate"
                type="button"
                @click="selectedDate = null; loadTodos()"
                style="
                  padding: 4px 8px;
                  background: var(--soft);
                  border: 1px solid var(--line);
                  border-radius: 4px;
                  color: var(--muted);
                  font-size: 12px;
                  cursor: pointer;
                  transition: all 0.2s;
                "
                @mouseenter="(e) => { e.currentTarget.style.background = 'var(--danger)'; e.currentTarget.style.color = '#fff'; }"
                @mouseleave="(e) => { e.currentTarget.style.background = 'var(--soft)'; e.currentTarget.style.color = 'var(--muted)'; }"
              >
                필터 해제
              </button>
            </div>
            <p style="margin: 0; font-size: 13px; color: var(--muted); line-height: 1.5">
              <strong>📅 일정 vs 📋 할일:</strong> 일정은 특정 날짜와 시간에 고정된 이벤트(예: 웨딩홀 방문, 드레스 피팅)이고, 
              할일은 매일매일 작게 쌓이는 체크리스트(예: 청첩장 주문 확인, 하객 명단 작성)입니다. 
              할일은 마감일이 설정되면 캘린더에도 표시됩니다.
              <span v-if="selectedDate" style="display: block; margin-top: 4px; color: var(--accent-2);">
                💡 캘린더에서 날짜를 클릭하면 해당 날짜의 일정만 표시됩니다.
              </span>
            </p>
          </div>
          <button class="btn primary" type="button" @click="openTodoModal" style="white-space: nowrap; flex-shrink: 0; align-self: flex-start;">할일 추가</button>
        </div>
        <div v-if="todos.length === 0" style="text-align: center; color: var(--muted); padding: 40px">
          할일이 없습니다.
        </div>
        <div v-else>
          <div
            v-for="todo in todos"
            :key="todo.id"
            class="todo-item"
            :class="{ completed: todo.is_completed }"
          >
            <div
              class="todo-checkbox"
              :class="{ checked: todo.is_completed }"
              @click.stop="toggleTodo(todo.id)"
            ></div>
            <div style="flex: 1; cursor: pointer" @click.stop="openTodoModal(todo)">
              <div style="font-weight: 600; margin-bottom: 4px">{{ todo.title }}</div>
              <div v-if="todo.due_date" style="font-size: 12px; color: var(--muted)">
                마감: {{ todo.due_date }}
              </div>
            </div>
            <div
              style="
                padding: 4px 8px;
                border-radius: 4px;
                font-size: 12px;
                background: var(--danger);
              "
              :style="{
                background:
                  todo.priority === 'high'
                    ? 'var(--danger)'
                    : todo.priority === 'medium'
                    ? 'var(--warn)'
                    : 'var(--ok)',
              }"
            >
              {{ todo.priority === 'high' ? '높음' : todo.priority === 'medium' ? '보통' : '낮음' }}
            </div>
            <div style="display: flex; gap: 6px; align-items: center; flex-shrink: 0;">
              <button
                type="button"
                @click.stop="openTodoModal(todo)"
                title="수정"
                style="
                  padding: 6px 10px;
                  background: var(--soft);
                  border: 1px solid var(--line);
                  border-radius: 6px;
                  color: var(--accent-2);
                  cursor: pointer;
                  transition: all 0.2s;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                  font-size: 13px;
                  font-weight: 500;
                  white-space: nowrap;
                "
                @mouseenter="(e) => { e.currentTarget.style.background = 'var(--accent)'; e.currentTarget.style.color = '#fff'; e.currentTarget.style.borderColor = 'var(--accent)'; }"
                @mouseleave="(e) => { e.currentTarget.style.background = 'var(--soft)'; e.currentTarget.style.color = 'var(--accent-2)'; e.currentTarget.style.borderColor = 'var(--line)'; }"
              >
                수정
              </button>
              <button
                type="button"
                @click.stop="deleteTodo(todo.id)"
                title="삭제"
                style="
                  padding: 6px 10px;
                  background: var(--soft);
                  border: 1px solid var(--line);
                  border-radius: 6px;
                  color: var(--danger);
                  cursor: pointer;
                  transition: all 0.2s;
                  display: flex;
                  align-items: center;
                  justify-content: center;
                  font-size: 13px;
                  font-weight: 500;
                  white-space: nowrap;
                "
                @mouseenter="(e) => { e.currentTarget.style.background = 'var(--danger)'; e.currentTarget.style.color = '#fff'; e.currentTarget.style.borderColor = 'var(--danger)'; }"
                @mouseleave="(e) => { e.currentTarget.style.background = 'var(--soft)'; e.currentTarget.style.color = 'var(--danger)'; e.currentTarget.style.borderColor = 'var(--line)'; }"
              >
                삭제
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 일정 추가 모달 -->
    <div v-if="showEventModal" class="modal-overlay" @click.self="closeEventModal">
      <div class="modal-card">
        <h3 style="margin-top: 0">{{ editingEventId ? '일정 수정' : '일정 추가' }}</h3>
        <div class="form-group">
          <label>제목</label>
          <input v-model="eventForm.title" type="text" required />
        </div>
        <div class="form-group">
          <label>날짜</label>
          <div class="input-with-icon">
            <input
              :value="eventForm.start_date"
              type="text"
              required
              placeholder="YYYY-MM-DD"
              maxlength="10"
              @keydown="handleDateKeydown($event, 'start_date')"
              @input="handleDateInput($event, 'start_date')"
              @paste="handleDatePaste($event, 'start_date')"
            />
            <span class="input-icon">📅</span>
          </div>
        </div>
        <div class="form-group">
          <label>시간</label>
          <div style="display: flex; gap: 8px; align-items: center">
            <div style="display: flex; gap: 4px; align-items: center; flex: 1">
              <input
                v-model="eventForm.timeHour"
                type="text"
                placeholder="시"
                maxlength="2"
                style="width: 60px; text-align: center"
                @input="(e) => {
                  const value = (e.target as HTMLInputElement).value.replace(/\D/g, '')
                  if (value.length > 2) {
                    eventForm.timeHour = value.slice(0, 2)
                  } else {
                    eventForm.timeHour = value
                  }
                  const hourNum = parseInt(value, 10)
                  if (!isNaN(hourNum)) {
                    // 13시 이상이면 자동으로 오후로 변경하고 12시간 형식으로 변환
                    if (hourNum >= 13 && hourNum <= 23) {
                      eventForm.timePeriod = 'PM'
                      eventForm.timeHour = String(hourNum - 12)
                    } else if (hourNum === 0) {
                      eventForm.timePeriod = 'AM'
                      eventForm.timeHour = '12'
                    } else if (hourNum > 23) {
                      eventForm.timeHour = '12'
                    } else if (hourNum > 12) {
                      eventForm.timeHour = '12'
                    }
                  }
                }"
              />
              <span style="color: var(--muted)">:</span>
              <input
                v-model="eventForm.timeMinute"
                type="text"
                placeholder="분"
                maxlength="2"
                style="width: 60px; text-align: center"
                @input="(e) => {
                  const value = (e.target as HTMLInputElement).value.replace(/\D/g, '')
                  if (value.length > 2) {
                    eventForm.timeMinute = value.slice(0, 2)
                  } else {
                    eventForm.timeMinute = value
                  }
                  const minuteNum = parseInt(value, 10)
                  if (!isNaN(minuteNum) && minuteNum > 59) {
                    eventForm.timeMinute = '59'
                  }
                }"
              />
            </div>
            <div style="display: flex; gap: 4px">
              <button
                type="button"
                class="btn"
                :class="{ primary: eventForm.timePeriod === 'AM' }"
                style="padding: 8px 16px; min-width: 60px"
                @click="eventForm.timePeriod = 'AM'"
              >
                오전
              </button>
              <button
                type="button"
                class="btn"
                :class="{ primary: eventForm.timePeriod === 'PM' }"
                style="padding: 8px 16px; min-width: 60px"
                @click="eventForm.timePeriod = 'PM'"
              >
                오후
              </button>
            </div>
          </div>
        </div>
        <div class="form-group">
          <label>카테고리</label>
          <select v-model="eventForm.category">
            <option value="general">일반</option>
            <option value="todo">할일</option>
            <option value="payment">결제</option>
            <option value="meeting">미팅</option>
            <option value="fitting">피팅</option>
            <option value="booking">예약</option>
            <option value="preparation">준비</option>
          </select>
        </div>
        <div class="form-group">
          <label>우선순위</label>
          <select v-model="eventForm.priority">
            <option value="low">낮음</option>
            <option value="medium">보통</option>
            <option value="high">높음</option>
          </select>
        </div>
        <div class="form-group">
          <label>담당자</label>
          <select v-model="eventForm.assignee">
            <option value="both">공동</option>
            <option value="groom">신랑</option>
            <option value="bride">신부</option>
          </select>
        </div>
        <div style="display: flex; gap: 8px; justify-content: flex-end; margin-top: 20px">
          <button class="btn" type="button" @click="closeEventModal">취소</button>
          <button
            v-if="editingEventId"
            class="btn danger"
            type="button"
            @click="deleteEvent(editingEventId)"
          >
            삭제
          </button>
          <button class="btn primary" type="button" @click="createEvent">
            {{ editingEventId ? '수정' : '추가' }}
          </button>
        </div>
      </div>
    </div>

  </section>
</template>

<style scoped>
.calendar-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 20px;
  gap: 16px;
}

.calendar-controls {
  display: flex;
  gap: 12px;
  align-items: center;
}

.month-navigation {
  display: flex;
  align-items: center;
  gap: 8px;
}

.month-btn {
  padding: 8px 12px;
  min-width: 40px;
  font-size: 16px;
  font-weight: 600;
}

.month-text {
  padding: 10px 16px;
  font-weight: 600;
  font-size: 16px;
  color: var(--text);
  min-width: 140px;
  text-align: center;
}

.wedding-date-section {
  display: flex;
  gap: 12px;
  align-items: center;
  margin-bottom: 24px;
  padding: 16px;
  background: rgba(139, 92, 246, 0.1);
  border-radius: 12px;
}

.wedding-date-section input {
  padding: 10px;
  border-radius: 8px;
  background: var(--soft);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: var(--text);
  font-size: 14px;
}

.calendar-grid {
  display: grid;
  grid-template-columns: repeat(7, 1fr);
  gap: 8px;
  margin-bottom: 20px;
}

.calendar-day {
  background: var(--soft);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 8px;
  padding: 12px;
  min-height: 100px;
  position: relative;
}

.calendar-day.other-month {
  opacity: 0.3;
}

.calendar-day.today {
  border-color: var(--accent);
  background: rgba(139, 92, 246, 0.1);
}

.calendar-day.selected-date {
  border-color: var(--accent-2);
  background: rgba(34, 211, 238, 0.15);
  border-width: 2px;
  cursor: pointer;
}

.calendar-day:hover {
  background: rgba(255, 255, 255, 0.05);
  cursor: pointer;
}

.calendar-day.selected-date:hover {
  background: rgba(34, 211, 238, 0.2);
}

.day-number {
  font-weight: 600;
  margin-bottom: 8px;
}

.event-item {
  font-size: 12px;
  padding: 6px 10px;
  background: var(--accent);
  border-radius: 6px;
  margin-bottom: 4px;
  cursor: pointer;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  color: #ffffff !important;
  font-weight: 600;
  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
  transition: all 0.2s ease;
  border: 1px solid rgba(255, 255, 255, 0.15);
  min-height: 24px;
  display: flex;
  align-items: center;
}

.event-item:hover {
  transform: translateY(-1px);
  box-shadow: 0 3px 8px rgba(0, 0, 0, 0.4);
  border-color: rgba(255, 255, 255, 0.3);
}

/* 담당자별 색상 (우선순위보다 우선) - 범례와 정확히 동일한 색상 */
.event-item.assignee-groom,
.calendar-day .event-item.assignee-groom {
  background: #3b82f6 !important; /* 파란색 - 신랑 (범례와 동일) */
  background-color: #3b82f6 !important;
  color: #ffffff !important;
  font-weight: 600;
  border: 1px solid rgba(255, 255, 255, 0.2);
  box-shadow: 0 2px 6px rgba(59, 130, 246, 0.4);
}

.event-item.assignee-bride,
.calendar-day .event-item.assignee-bride {
  background: #ec4899 !important; /* 핑크색 - 신부 (범례와 동일) */
  background-color: #ec4899 !important;
  color: #ffffff !important;
  font-weight: 600;
  border: 1px solid rgba(255, 255, 255, 0.2);
  box-shadow: 0 2px 6px rgba(236, 72, 153, 0.4);
}

.event-item.assignee-both,
.calendar-day .event-item.assignee-both {
  background: #8b5cf6 !important; /* 보라색 - 공동 (범례와 동일) */
  background-color: #8b5cf6 !important;
  color: #ffffff !important;
  font-weight: 600;
  border: 1px solid rgba(255, 255, 255, 0.2);
  box-shadow: 0 2px 6px rgba(139, 92, 246, 0.4);
}

/* 우선순위별 투명도 조정 - 가독성을 위해 투명도 제거 */
.event-item.assignee-groom.high,
.event-item.assignee-bride.high,
.event-item.assignee-both.high,
.event-item.assignee-groom.medium,
.event-item.assignee-bride.medium,
.event-item.assignee-both.medium,
.event-item.assignee-groom.low,
.event-item.assignee-bride.low,
.event-item.assignee-both.low {
  opacity: 1;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.3);
}

/* 담당자가 없는 경우 우선순위 색상 사용 */
.event-item.high:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: var(--danger) !important;
  color: #ffffff !important;
  font-weight: 600;
}

/* 다크 모드에서 더 밝게 */
[data-theme="dark"] .event-item.high:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: #f87171 !important; /* 더 밝은 빨간색 */
  box-shadow: 0 2px 6px rgba(248, 113, 113, 0.4);
}

.event-item.medium:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: var(--warn) !important;
  color: #ffffff !important;
  font-weight: 600;
}

/* 다크 모드에서 더 밝게 */
[data-theme="dark"] .event-item.medium:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: #fbbf24 !important; /* 더 밝은 노란색 */
  box-shadow: 0 2px 6px rgba(251, 191, 36, 0.4);
}

.event-item.low:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: var(--ok) !important;
  color: #ffffff !important;
  font-weight: 600;
}

/* 다크 모드에서 더 밝게 */
[data-theme="dark"] .event-item.low:not(.assignee-groom):not(.assignee-bride):not(.assignee-both):not(.wedding-date) {
  background: #34d399 !important; /* 더 밝은 초록색 */
  box-shadow: 0 2px 6px rgba(52, 211, 153, 0.4);
}

/* 예식일 이벤트 특별 스타일 */
.event-item.wedding-event,
.event-item.wedding-date {
  background: linear-gradient(135deg, var(--accent), var(--accent-2)) !important;
  color: #ffffff !important;
  font-weight: 700;
  font-size: 13px;
  box-shadow: 0 2px 8px rgba(var(--accent-rgb), 0.5);
  transform: scale(1.02);
  transition: all 0.2s ease;
  text-shadow: 0 1px 2px rgba(0, 0, 0, 0.3);
  cursor: default;
}

/* 라이트 모드에서 예식일 색상 더 진하게 */
[data-theme="light"] .event-item.wedding-event,
[data-theme="light"] .event-item.wedding-date {
  background: linear-gradient(135deg, #b8860b, #daa520) !important; /* 더 진한 골드 색상 */
  box-shadow: 0 2px 8px rgba(184, 134, 11, 0.4);
}

.event-item.wedding-event:hover,
.event-item.wedding-date:hover {
  transform: scale(1.05);
  box-shadow: 0 4px 12px rgba(var(--accent-rgb), 0.6);
}

[data-theme="light"] .event-item.wedding-event:hover,
[data-theme="light"] .event-item.wedding-date:hover {
  box-shadow: 0 4px 12px rgba(184, 134, 11, 0.5);
}

.todo-section {
  margin-top: 24px;
}

.todo-item {
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 12px;
  background: var(--soft);
  border-radius: 8px;
  margin-bottom: 8px;
}

.todo-item.completed {
  opacity: 0.5;
}

.todo-checkbox {
  width: 20px;
  height: 20px;
  border-radius: 4px;
  border: 2px solid var(--accent);
  cursor: pointer;
}

.todo-checkbox.checked {
  background: var(--accent);
}

.form-group select {
  width: 100%;
  padding: 10px 12px;
  border-radius: 8px;
  background: var(--soft);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: var(--text);
  font-size: 14px;
  font-family: inherit;
  cursor: pointer;
  appearance: none;
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%23a7b0c0' d='M6 9L1 4h10z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-position: right 12px center;
  padding-right: 36px;
  transition: 0.2s;
}

.form-group select:hover {
  border-color: rgba(255, 255, 255, 0.2);
}

.form-group select:focus {
  outline: none;
  border-color: var(--accent);
  box-shadow: 0 0 0 3px rgba(139, 92, 246, 0.1);
}

[data-theme='light'] .form-group select {
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 12 12'%3E%3Cpath fill='%235d6175' d='M6 9L1 4h10z'/%3E%3C/svg%3E");
}

.input-with-icon {
  position: relative;
  width: 100%;
}

.input-with-icon input {
  width: 100%;
  padding: 10px 36px 10px 12px;
  border-radius: 8px;
  background: var(--soft);
  border: 1px solid rgba(255, 255, 255, 0.1);
  color: var(--text);
  font-size: 14px;
  font-family: inherit;
}

.input-icon {
  position: absolute;
  right: 12px;
  top: 50%;
  transform: translateY(-50%);
  pointer-events: none;
  font-size: 16px;
}

/* 모바일 스타일 */
@media (max-width: 768px) {
  .section {
    padding: 16px 8px;
  }

  .container {
    padding: 0 12px;
  }

  .page-title h1 {
    font-size: 22px;
    margin-bottom: 6px;
    font-weight: 700;
  }

  .page-title p {
    font-size: 14px;
  }

  .card {
    padding: 16px;
    margin-bottom: 16px;
  }

  .card h2 {
    font-size: 18px;
    font-weight: 600;
  }

  .wedding-date-section {
    flex-direction: column;
    gap: 10px;
    padding: 14px;
    margin-bottom: 16px;
  }

  .wedding-date-section label {
    width: 100%;
    margin-left: 0;
    font-size: 15px;
    font-weight: 600;
  }

  .wedding-date-section input {
    width: 100%;
    padding: 12px;
    font-size: 16px;
  }

  .wedding-date-section button {
    width: 100%;
    font-size: 15px;
    padding: 12px;
    min-height: 48px;
  }

  .wedding-date-section > div[style*="font-size: 18px"] {
    font-size: 20px !important;
    font-weight: 700;
  }

  .calendar-header {
    flex-direction: column;
    gap: 12px;
    align-items: flex-start;
  }

  .calendar-header h2 {
    font-size: 18px;
  }

  .calendar-controls {
    width: 100%;
    flex-direction: column;
    gap: 10px;
  }

  .month-navigation {
    width: 100%;
    justify-content: center;
    gap: 12px;
  }

  .month-btn {
    width: 48px;
    height: 48px;
    font-size: 18px;
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .month-text {
    font-size: 18px;
    font-weight: 700;
    padding: 12px 20px;
    min-width: auto;
    flex: 1;
    text-align: center;
  }

  .calendar-controls > .btn.primary {
    width: 100%;
    font-size: 15px;
    padding: 12px;
  }

  .card > div[style*="display: flex"][style*="gap: 16px"][style*="flex-wrap"] {
    font-size: 13px;
  }

  .card > div[style*="display: flex"][style*="gap: 16px"][style*="flex-wrap"] > div {
    font-size: 13px;
  }

  .card > div[style*="display: flex"][style*="gap: 16px"][style*="flex-wrap"] > div > div {
    font-size: 13px;
  }

  .card > div[style*="display: flex"][style*="gap: 16px"][style*="flex-wrap"] > div > span {
    font-size: 13px;
  }

  .calendar-grid {
    gap: 4px;
  }

  .calendar-grid > div[style*="text-align: center"] {
    font-size: 14px;
    font-weight: 600;
    padding: 10px 4px;
  }

  .calendar-day {
    padding: 8px 4px;
    min-height: 70px;
  }

  .day-number {
    font-size: 15px;
    font-weight: 700;
    margin-bottom: 6px;
  }

  .event-item {
    font-size: 11px;
    padding: 5px 6px;
    margin-bottom: 3px;
    min-height: 22px;
    font-weight: 600;
    line-height: 1.3;
  }

  .todo-section {
    margin-top: 16px;
  }

  .todo-section h2 {
    font-size: 18px;
    font-weight: 600;
  }

  .todo-section > div[style*="display: flex"] > div > div[style*="display: flex"] > span {
    font-size: 14px;
    font-weight: 600;
  }

  .todo-section > div[style*="display: flex"] > div > p {
    font-size: 13px;
    line-height: 1.6;
  }

  .todo-item {
    padding: 12px;
    gap: 10px;
    flex-wrap: wrap;
  }

  .todo-checkbox {
    width: 20px;
    height: 20px;
  }

  .todo-item > div[style*="flex: 1"] > div[style*="font-weight: 600"] {
    font-size: 15px;
    font-weight: 600;
  }

  .todo-item > div[style*="flex: 1"] > div[style*="font-size: 12px"] {
    font-size: 13px;
  }

  .todo-item > div[style*="padding: 4px 8px"] {
    font-size: 12px;
    padding: 6px 10px;
  }

  .todo-item > div[style*="display: flex"][style*="gap: 6px"] {
    flex-direction: column;
    gap: 8px;
    width: 100%;
  }

  .todo-item > div[style*="display: flex"][style*="gap: 6px"] > button {
    width: 100%;
    font-size: 14px;
    padding: 10px;
    min-height: 44px;
  }

  .modal-card {
    padding: 20px 16px;
    width: 95%;
    max-width: none;
  }

  .modal-card h3 {
    font-size: 20px;
    font-weight: 700;
  }

  .form-group {
    margin-bottom: 14px;
  }

  .form-group label {
    font-size: 15px;
    font-weight: 600;
    margin-bottom: 8px;
  }

  .form-group input,
  .form-group select,
  .form-group textarea {
    padding: 12px;
    font-size: 16px;
  }

  .form-group > div[style*="display: flex"] {
    flex-direction: column;
    gap: 10px;
  }

  .form-group > div[style*="display: flex"] > div {
    width: 100%;
  }

  .form-group > div[style*="display: flex"] > button {
    width: 100%;
    font-size: 14px;
    padding: 12px;
  }

  .btn {
    padding: 12px 16px;
    font-size: 15px;
    min-height: 48px;
  }

  .card > div[style*="display: flex"] {
    flex-direction: column;
    gap: 10px;
  }

  .card > div[style*="display: flex"] > button {
    width: 100%;
    font-size: 15px;
    padding: 12px;
  }
}

@media (max-width: 480px) {
  .page-title h1 {
    font-size: 20px;
  }

  .card h2 {
    font-size: 16px;
  }

  .calendar-day {
    min-height: 65px;
    padding: 6px 3px;
  }

  .day-number {
    font-size: 14px;
  }

  .event-item {
    font-size: 10px;
    padding: 4px 5px;
    min-height: 20px;
  }

  .calendar-grid > div[style*="text-align: center"] {
    font-size: 12px;
    padding: 8px 2px;
  }

  .todo-item > div[style*="flex: 1"] > div[style*="font-weight: 600"] {
    font-size: 14px;
  }
}
</style>
